name: Export Firestore Database and Send Firebase Messaging Notification

on:
  schedule:
    - cron: '0 */4 * * *' # Запускать каждые 4 часа
  workflow_dispatch: # Запускать вручную

jobs:
  export-firestore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Export Firestore Database
        run: |
          npm install -g firebase-tools
          firebase login:ci --no-localhost --headless > /dev/null 2>&1
          collections=$(firebase firestore:list --format=json | jq -r '.[].name')
          for collection in $collections; do
            filename=$(echo $collection | cut -d "/" -f 2).json
            firebase firestore:export --collection-id=$collection --format=json /tmp/$filename
            mv /tmp/$filename app/src/assets/settings/
          done

      - name: Send Firebase Messaging Notification
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
        run: |
          npm install firebase-admin
          node ./sendFirebaseMessage.js
          
      - name: Commit Changes
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@github.com'
          git add app/src/assets/settings/
          git commit -m 'Export Firestore Database'
          git push origin main